import './js/bootstrap.bundle';
import './js/bootstrap.bundle.min.js';
import './js/canvas.js';
import './js/script.js';
// import './js/swiper-bundle.min.js';
import './js/yamap.js';
import './js/app'

import './css/about-tea.css';
import './css/about-brand.css';
import './css/animation.css';
import './css/bootstrap.css';
import './css/bootstrap.min.css';
import './css/catalog.css';
import './css/contacts.css';
import './css/footer.css';
import './css/menu.css';
import './css/product.css';
import './css/recept.css';
import './css/search.css';
import './css/slider.css';
import './css/steam.css';
import './css/button.css';
import './css/star.css';
import './css/in-development.css';
import './css/style.css';
import './css/module-tea-sl-swiper_mobile.css';
import './css/module-tea-sl-slider.css';
import './css/module-product-card-description.css';
import './css/module-catalog-packs-cards.css';
import './css/module-breadcrumbs.css';
import './css/product-card.css';
import './css/module-recipes.css';
// import './css/swiper-bundle.min.css';